### ISSUE TITLE
Question: What could cause an instruction to be skipped?

### ISSUE THREAD

**Issue by fschutt** [gurugio/book_assembly_8086#9]
I'm sorry if this isn't the right place to ask, but it's hard getting someone with assembly experience.

I'm going through the tutorials (thanks a lot!) and I have this code:

```asm
org 100h
mov ax, 0800h
mov ds, ax
mov si, c[3]
ret

c DW 5 DUP(09h)
```

When I'm stepping through the code, the instruction `mov si, c[3]` doesn't do anything (I'd expect it to set SI to 0009). If I write it like this, however:

```asm
org 100h
mov si, c[3]
ret

c DW 5 DUP(09h)
```

... then it works. Is this intended somehow or is this a bug in the emulator? Does SI depend on other things to be set to certain values? If I use `ax` instead of `si`, it only changes `ah` for some reason. Could you replicate this or is this intentional? Thanks in advance.

**Comment by gurugio** [comment]
mov ax, 0800h
mov ds, ax
Those commands set ds=0800h.
So, "mov si, c[3]" command is "mov si, ds:c[3]", and it means "mov si, 0800:c[3]".
What is the address of c array?
Is the segment address of c array 0800h?

The second source does not change the segment address.
So it can read the c array.

**Comment by fschutt** [comment]
Thanks a lot for the answer!
